apiVersion: 1
datasources:
  - name: InfluxDB-OpenHAB
    uid: influxdb-openhab
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: openhab
      defaultBucket: openhab
      tlsSkipVerify: true
      timeInterval: "1m"
    secureJsonData:
      token: "openhab-influx-token-change-me"
