apiVersion: 1
datasources:
  - name: InfluxDB-SmartGrid
    uid: influxdb-smartgrid
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: openhab
      defaultBucket: smartgrid
      tlsSkipVerify: true
      timeInterval: "10s"
    secureJsonData:
      token: "smartgrid-token-change-me"
